api/urls.py
from smarturls import surl as url

from . import views


urlpatterns = (
    url(
        r'/events/<slug:slug>/schedule/',
        views.RetrieveEventScheduleView.as_view(),
        name='api_view_event_schedule'
    ),
    url(
        r'/events/<slug:slug>/activities/',
        views.CreateActivityView.as_view(),
        name='api_event_create_activity'
    ),
    url(
        r'/events/<slug:event_slug>/activities/<slug:slug>/',
        views.ActivityView.as_view(),
        name='api_event_activity'
    ),
)

deck/urls.py
from smarturls import surl as url

from . import views

urlpatterns = (
    url(regex=r'/my_proposals/',
        view=views.ListMyProposals.as_view(),
        name='my_proposals'),
    url(regex=r'/my_events/',
        view=views.ListMyEvents.as_view(),
        name='my_events'),
    url(regex=r'/events/',
        view=views.ListEvents.as_view(template_name='event/event_list.html'),
        name='list_events'),
    url(regex=r'/past_events/',
        view=views.ListEvents.as_view(
            template_name='event/past_event_list.html',
            past_events=True),
        name='past_events'),
    url(regex=r'/events/create/',
        view=views.CreateEvent.as_view(),
        name='create_event'),
    url(regex=r'/events/<slug:slug>/',
        view=views.DetailEvent.as_view(),
        name='view_event'),
    url(regex=r'/events/<slug:slug>/update/',
        view=views.UpdateEvent.as_view(),
        name='update_event'),
    url(regex=r'/events/<slug:slug>/delete/',
        view=views.DeleteEvent.as_view(),
        name='delete_event'),
    url(regex=r'/events/<slug:slug>/export/',
        view=views.ExportEvent.as_view(),
        name='export_event'),
    url(regex=r'/events/<slug:slug>/create_schedule/',
        view=views.CreateEventSchedule.as_view(),
        name='create_event_schedule'),
    url(regex=r'/events/<slug:slug>/proposals/create/',
        view=views.CreateProposal.as_view(),
        name='create_event_proposal'),
    url(regex=r'/events/<slug:slug>/schedule/',
        view=views.DetailEventSchedule.as_view(),
        name='view_event_schedule'),
    url(regex=r'/events/<slug:event_slug>/'
              r'proposals/<slug:slug>/update/',
        view=views.UpdateProposal.as_view(),
        name='update_proposal'),
    url(regex=r'/events/<slug:event_slug>/'
              r'proposals/<slug:slug>/delete/',
        view=views.DeleteProposal.as_view(),
        name='delete_proposal'),
    url(regex=r'/events/<slug:event_slug>/'
              r'proposals/<slug:slug>/rate/<slug:rate>/',
        view=views.RateProposal.as_view(),
        name='rate_proposal'),
    url(regex=r'/events/<slug:event_slug>/'
              r'proposals/<slug:slug>/approve_proposal/',
        view=views.ApproveProposal.as_view(),
        name='approve_proposal'),
    url(regex=r'/events/<slug:event_slug>/'
              r'proposals/<slug:slug>/disapprove_proposal/',
        view=views.DisapproveProposal.as_view(),
        name='disapprove_proposal'),
)

speakerfight/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import static


urlpatterns = (
    url(r'^admin/', admin.site.urls),

    url(r'^accounts/', include('allauth.urls')),

    url(r'^', include('core.urls')),
    url(r'^', include('deck.urls')),
    url(r'^', include('jury.urls')),
    url(r'^organizations/', include('organization.urls')),
    url(r'^api/', include('api.urls')),
)

urlpatterns += tuple(
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

if settings.DEBUG:
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += (
            url(r'^__debug__/', include(debug_toolbar.urls)),
        )

deck/models.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.contrib.auth.models import AnonymousUser
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db import models, transaction
from django.db.models import Count
from django.db.models.aggregates import Sum
from django.db.models.signals import post_delete, post_save
from django.dispatch import receiver
from django.template.loader import render_to_string
from django.utils.translation import ugettext as _
from django.utils import timezone, six
from django.utils.encoding import python_2_unicode_compatible

from django_extensions.db.fields import AutoSlugField

from allauth.account.signals import user_signed_up

from textwrap import dedent

from jury.models import Jury



class DeckBaseManager(models.QuerySet):
    def cached_authors(self):
        return super(DeckBaseManager, self).select_related('author')

    def published_ones(self):
        return self.cached_authors().filter(is_published=True)

    def upcoming(self, published_only=True):
        return self.filter(closing_date__gte=timezone.now(), is_published=published_only)

    def order_by_never_voted(self, user_id):
        if self.model != Proposal:
            raise AttributeError(
                "%s object has no attribute %s" % (
                    self.model, 'order_by_never_voted'))

        order_by_criteria = dedent("""
            SELECT 1
              FROM deck_vote
             WHERE deck_vote.user_id = %s AND
                   deck_vote.proposal_id = deck_proposal.activity_ptr_id
             LIMIT 1
        """)

        new_ordering = ['-never_voted']
        if settings.DATABASES['default'].get('ENGINE') == 'django.db.backends.sqlite3':
            new_ordering = ['never_voted']
        new_ordering.extend(Proposal._meta.ordering)
        return self.extra(
            select=dict(never_voted=order_by_criteria % user_id),
            order_by=new_ordering
        )


@python_2_unicode_compatible
class DeckBaseModel(models.Model):
    title = models.CharField(_('Title'), max_length=200)
    slug = AutoSlugField(populate_from='title', overwrite=True,
                         max_length=200, unique=True, db_index=True)
    description = models.TextField(
        _('Description'), max_length=10000, blank=True)
    created_at = models.DateTimeField(_('Created At'), auto_now_add=True)
    is_published = models.BooleanField(_('Publish'), default=True)

    # relations
    author = models.ForeignKey(to=settings.AUTH_USER_MODEL,
                               related_name='%(class)ss')

    # managers
    objects = DeckBaseManager.as_manager()

    class Meta:
        abstract = True

    def __str__(self):
        return six.text_type(self.title)


@python_2_unicode_compatible
class Vote(models.Model):
    ANGRY, SLEEPY, SAD, HAPPY, LAUGHING = range(-1, 4)
    VOTE_TITLES = dict(
        angry=_('Angry'), sad=_('Sad'),
        sleepy=_('Sleepy'), happy=_('Happy'),
        laughing=_('Laughing')
    )
    VOTE_RATES = ((ANGRY, 'angry'),
                  (SAD, 'sad'),
                  (SLEEPY, 'sleepy'),
                  (HAPPY, 'happy'),
                  (LAUGHING, 'laughing'))
    rate = models.SmallIntegerField(_('Rate Index'), null=True, blank=True,
                                    choices=VOTE_RATES)

    # relations
    proposal = models.ForeignKey(to='deck.Proposal', related_name='votes')
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='votes')

    class Meta:
        verbose_name = _('Vote')
        verbose_name_plural = _('Votes')
        unique_together = (('proposal', 'user'),)

    def __str__(self):
        return six.text_type("{0.user}: {0.rate} in {0.proposal}".format(self))

    def save(self, *args, **kwargs):
        validation_message = None

        user_is_in_jury = self.proposal.event.jury.users.filter(
            pk=self.user.pk).exists()
        if (self.user.is_superuser or user_is_in_jury):
            pass
        elif self.user == self.proposal.author:
            validation_message = _(u'You cannot Rate your own proposals.')
        elif not self.proposal.event.allow_public_voting:
            validation_message = _(u"Proposal doesn't accept Public Voting.")

        if validation_message:
            raise ValidationError(_(validation_message))

        return super(Vote, self).save(*args, **kwargs)


def get_activities_by_parameters_order(ids):
    activities = []
    for id_ in ids:
        activities.append(
            Activity.objects.get(id=id_)
        )
    return activities


class Activity(DeckBaseModel):
    PROPOSAL = 'proposal'
    WORKSHOP = 'workshop'
    OPENNING = 'openning'
    COFFEEBREAK = 'coffee-break'
    LUNCH = 'lunch'
    LIGHTNINGTALKS = 'lightning-talks'
    ENDING = 'ending'
    ACTIVITY_TYPES = (
        (PROPOSAL, _('Proposal')),
        (WORKSHOP, _('Workshop')),
        (OPENNING, _('Openning')),
        (COFFEEBREAK, _('Coffee Break')),
        (LUNCH, _('Lunch')),
        (LIGHTNINGTALKS, _('Lightning Talks')),
        (ENDING, _('Ending')),
    )
    start_timetable = models.TimeField(
        _('Start Timetable'), null=True, blank=False)
    end_timetable = models.TimeField(
        _('End Timetable'), null=True, blank=False)
    track_order = models.SmallIntegerField(_('Order'), null=True, blank=True)
    activity_type = models.CharField(
        _('Type'), choices=ACTIVITY_TYPES, default=PROPOSAL, max_length=50)

    # relations
    track = models.ForeignKey(to='deck.Track', related_name='activities',
                              null=True, blank=True)

    class Meta:
        ordering = ('track_order', 'start_timetable', 'pk')
        verbose_name = _('Activity')
        verbose_name_plural = _('Activities')

    @property
    def timetable(self):
        if all([self.start_timetable is None, self.end_timetable is None]):
            return '--:--'

        return '{0} - {1}'.format(
            self.start_timetable.strftime('%H:%M'),
            self.end_timetable.strftime('%H:%M')
        )

    @property
    def is_proposal(self):
        return self.activity_type == self.PROPOSAL


class Proposal(Activity):
    is_approved = models.BooleanField(_('Is approved'), default=False)
    more_information = models.TextField(
        _('More information'), max_length=10000, null=True, blank=True)
    slides_url = models.CharField(
        _('speakerdeck.com/'), max_length=250, null=True, blank=True)

    def get_full_slides_url(self):
        if self.slides_url:
            return 'http://www.speakerdeck.com/{0}'.format(self.slides_url)

    # relations
    event = models.ForeignKey(to='deck.Event', related_name='proposals')

    class Meta:
        ordering = ['title']
        verbose_name = _('Proposal')
        verbose_name_plural = _('Proposals')

    def save(self, *args, **kwargs):
        if not self.pk and self.event.closing_date_is_passed:
            raise ValidationError(
                _("This Event doesn't accept Proposals anymore."))
        return super(Proposal, self).save(*args, **kwargs)

    @property
    def get_rate(self):
        rate = None
        try:
            rate = self.votes__rate__sum
        except AttributeError:
            rate = self.votes.aggregate(Sum('rate'))['rate__sum']
        finally:
            return rate or 0

    def rate(self, user, rate):
        rate_int = [r[0] for r in Vote.VOTE_RATES if rate in r][0]
        with transaction.atomic():
            self.votes.update_or_create(user=user, defaults={'rate': rate_int})

    def user_already_voted(self, user):
        if isinstance(user, AnonymousUser):
            return False
        return self.votes.filter(user=user).exists()

    def user_can_vote(self, user):
        can_vote = False
        if self.author == user and not self.event.author == user:
            pass
        elif self.event.allow_public_voting:
            can_vote = True
        elif user.is_superuser:
            can_vote = True
        elif self.event.jury.users.filter(pk=user.pk).exists():
            can_vote = True
        return can_vote

    def user_can_approve(self, user):
        can_approve = False
        if user.is_superuser:
            can_approve = True
        elif self.event.jury.users.filter(pk=user.pk).exists():
            can_approve = True
        return can_approve

    def get_absolute_url(self):
        return reverse('view_event', kwargs={'slug': self.event.slug}) + \
            '#' + self.slug

    def approve(self):
        if self.is_approved:
            raise ValidationError(_("This Proposal was already approved."))
        self.is_approved = True
        self.save()

    def disapprove(self):
        if not self.is_approved:
            raise ValidationError(_("This Proposal was already disapproved."))
        self.is_approved = False
        self.save()


@python_2_unicode_compatible
class Track(models.Model):
    title = models.CharField(_('Title'), max_length=200)
    slug = AutoSlugField(populate_from='title', overwrite=True,
                         max_length=200, unique=True, db_index=True)

    # relations
    event = models.ForeignKey(to='deck.Event', related_name='tracks')

    class Meta:
        verbose_name = _('Track')
        verbose_name_plural = _('Tracks')

    def __str__(self):
        return six.text_type('Track for: "%s"' % self.event.title)

    @property
    def proposals(self):
        return Proposal.objects.filter(
            pk__in=self.activities.values_list('pk', flat=True)
        )

    def has_activities(self):
        return self.activities.exists()

    def add_proposal_to_slot(self, proposal, slot_index):
        proposal.track = self
        proposal.is_approved = True
        proposal.track_order = slot_index
        proposal.save()

deck/forms.py
from django import forms
from django.utils.translation import ugettext as _
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User

from datetimewidget.widgets import DateTimeWidget

from .models import Event, Proposal, Activity


class CustomDateTimeWidget(DateTimeWidget):
    def format_output(self, *args, **kwargs):
        return super(CustomDateTimeWidget, self)\
            .format_output(*args, **kwargs).replace(
                '<i class="icon-th"></i>', '<i class="icon-th hide"></i>')


class CustomTimeInputWidget(forms.TimeInput):
    input_type = 'time'


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        exclude = ['author', 'jury']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'inline-input'}),
            'closing_date': CustomDateTimeWidget(attrs={
                'id': 'id_closing_date',
                'class': 'inline-input',
                'placeholder': 'Closing Date'
            }),
        }


class InviteForm(forms.ModelForm):
    email = forms.EmailField(label=_('User email'))

    class Meta:
        model = Event
        fields = []

    def add_to_jury(self):
        email = self.cleaned_data.get('email')
        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            raise ValidationError(
                _(u'The "%s" are not a Speakerfight user. '
                  u'For now, we just allow already joined users.') % email)
        if self.instance.jury.users.filter(pk=user.pk).exists():
            raise ValidationError(
                _(u'The "@%s" already is being part of this jury.') % user)
        self.instance.jury.users.add(user)


class ProposalForm(forms.ModelForm):
    description = forms.CharField(required=True, widget=forms.Textarea())

    class Meta:
        model = Proposal
        exclude = [
            'event', 'author', 'track', 'rate',
            'is_approved', 'track_order',
            'activity_type', 'start_timetable', 'end_timetable',
        ]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'inline-input'}),
            'slides_url': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'jane_doe/talk',
                }),
        }


class ActivityForm(forms.ModelForm):
    # Removing the Proposal type from the available options
    activity_type = forms.ChoiceField(
        choices=[actitvity_type for actitvity_type in Activity.ACTIVITY_TYPES
                 if actitvity_type[0] != Activity.PROPOSAL])

    class Meta:
        model = Activity
        fields = [
            'title', 'description', 'activity_type',
            'start_timetable', 'end_timetable',
        ]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'inline-input'}),
            'start_timetable': CustomTimeInputWidget(format='%H:%M'),
            'end_timetable': CustomTimeInputWidget(format='%H:%M'),
        }


class ActivityTimetableForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = [
            'start_timetable', 'end_timetable',
        ]
        widgets = {
            'start_timetable': CustomTimeInputWidget(format='%H:%M'),
            'end_timetable': CustomTimeInputWidget(format='%H:%M'),
        }

deck/templates/event/event_confirm_delete.html
{% extends "layout.html" %}

{% load i18n %}
{% load bootstrap3 %}

{% block head_title %}{% trans "Delete Event" %}: "{{ object }}"{% endblock %}

{% block content %}
  <div class="row">
    <h1>{% trans "Delete Event" %}: "{{ object }}"</h1>
    <p>{% trans "Are you sure you want to delete this event?" %}</p>
    <p>{% trans "After deleting this event all proposals will be lost forever." %}</p>
    <form method="POST">
      {% csrf_token %}
      {% buttons %}
        <button type="submit" class="btn-flat success text-upper">
          <i class="icon icon-trash"></i>
          {% trans "Delete" %}
        </button>
        <div class="pull-right">
          <a href="{% url 'view_event' slug=object.slug %}" class="link text-upper">
            <i class="icon-calendar"></i>
            {% trans "event detail" %}
          </a>
        </div>
      {% endbuttons %}
    </form>
  </div>
{% endblock content %}

deck/templates/event/event_detail.html
{% extends "layout.html" %}
{% load staticfiles %}

{% load i18n %}
{% load bootstrap3 %}
{% load deck_tags %}

{% block head %}
  <style type="text/css">
    tr td.first-has-no-border:first-child {
      border-top: none;
    }
  </style>
  <!-- Go to www.addthis.com/dashboard to customize your tools -->
  <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4f777bac7bca077f" async="async"></script>
  <link rel="stylesheet" href="{% static 'css/proposals.css' %}" type="text/css" media="screen" />
{% endblock head %}

{% block head_title %}{{ event }}{% endblock %}

{% block content %}
  <ol class="breadcrumb">
    <li><a href="{% url 'index_page' %}">{% trans "Home" %}</a></li>
    <li><a href="{% url 'list_events' %}">{% trans "Events" %}</a></li>
    <li class="active">{{ event.title }}</li>
  </ol>

  <!-- header -->
  <div class="row" id="event-detail">
    <div class="col-md-12">
      {% include "event/snippets/event_list_item.html" with event_detail=True %}
    </div>

    {% if not event.allow_public_voting %}
    <div class="col-md-12">
      <div class="alert alert-warning">
        <i class="icon-eye-close"></i>
        {% blocktrans %}
          This event doesn't accept <strong>Public Voting</strong>, because of this you can only see your own proposals.
        {% endblocktrans %}
      </div>
    </div>
    {% endif %}

    {% if event.anonymous_voting %}
    <div class="col-md-12">
      <div class="alert alert-warning">
        <i class="icon-eye-close"></i>
        {% blocktrans %}
          This event is in the <strong>Anonymous Voting</strong> mode, all the speakers are hidden for voting, you should base your vote just in the content of the proposals.
        {% endblocktrans %}
      </div>
    </div>
    {% endif %}

    <div class="col-md-10 col-md-offset-1">
      <div class="event-proposals-header">
        {% if event.closing_date_is_passed %}
          <span class="pull-right text-danger">
            <i class="icon-warning-sign"></i>
            {% trans "The event is no longer accepting proposals." %}
          </span>
        {% else %}
          <a class="btn-flat success pull-right text-upper" href="{% url 'create_event_proposal' slug=event.slug %}">
            <i class="icon-plus"></i>
            {% trans "Send a proposal" %}
          </a>
        {% endif %}

        <h3>{% trans "Proposals" %}</h3>
      </div>

      <div id="event-proposals">
        {% for proposal in event_proposals %}
          <div id="{{ proposal.slug }}" class="panel panel-default proposal-item">
            <div class="panel-body">
              {% if not event.anonymous_voting %}
              <img src="{{ proposal.author|get_user_photo }}" alt="author photo" class="img-circle pull-right author-photo">
              {% endif %}
              <h3 class="panel-title proposal-title">
                <a href="#{{ proposal.slug }}">
                  {{ proposal }}
                </a>
              </h3>
              <p class="proposal-metadata">
                {% if not event.anonymous_voting and proposal.get_full_slides_url is not None %}
                  {% blocktrans with slides_url=proposal.get_full_slides_url profile_url=proposal.author.profile.get_absolute_url author=proposal.author.get_full_name|default:proposal.author.username created_at=proposal.created_at %}
                  <a href="{{ slides_url }}" target="_blank">See presentation on Speakerdeck</a>.<br>
                  Proposed by <strong><a href="{{ profile_url }}">{{ author }}</a></strong> at {{ created_at }}.
                  {% endblocktrans %}
                {% elif not event.anonymous_voting %}
                  {% blocktrans with profile_url=proposal.author.profile.get_absolute_url author=proposal.author.get_full_name|default:proposal.author.username created_at=proposal.created_at %}
                  Proposed by <strong><a href="{{ profile_url }}">{{ author }}</a></strong> at {{ created_at }}.
                  {% endblocktrans %}
                {% else %}
                  {% blocktrans with created_at=proposal.created_at %}
                  Proposed at {{ created_at }}.
                  {% endblocktrans %}
                {% endif %}
                {% if event.author_id == request.user.id or event|is_user_in_jury:request.user or request.user.is_superuser %}
                  {% if proposal.more_information %}
                    <br>
                    <blockquote>{{ '* '|add:proposal.more_information|safe|linebreaks }}</blockquote>
                  {% endif %}
                  <br>
                  {% with votes_count=proposal.votes.count %}
                    {% if votes_count > 0 %}
                      {% blocktrans with votes_count=votes_count vote_pluralize=votes_count|pluralize %}
                        This proposal already received {{ votes_count }} vote{{ vote_pluralize }}.
                      {% endblocktrans %}
                    {% else %}
                      {% trans "This proposal never received a vote." %}
                    {% endif %}
                  {% endwith %}
                {% endif %}
              </p>
              <div class="proposal-description">
                {{ proposal.description|safe|linebreaks }}
              </div>
              {% include "event/vote_block.html" %}
            </div>
            {% if request.user in event.jury.users or request.user.is_superuser or proposal.author_id == request.user.id %}
              <div class="panel-footer proposal-actions text-center">
                {% if request.user in event.jury.users or request.user.is_superuser %}
                  {% if proposal.is_approved %}
                    <a href="{% url 'disapprove_proposal' event_slug=event.slug slug=proposal.slug %}" class="btn-flat gray text-upper disapprove-link" data-toggle="tooltip" title="{% trans 'Disapprove the proposal.' %}">
                      <i class="icon-check-empty"></i>
                      <span>{% trans "Disapprove" %}</span>
                    </a>
                  {% else %}
                    <a href="{% url 'approve_proposal' event_slug=event.slug slug=proposal.slug %}" class="btn-flat gray text-upper approve-link" data-toggle="tooltip" title="{% trans 'Approve the proposal.' %}">
                      <i class="icon-check"></i>
                      <span>{% trans "Approve" %}</span>
                    </a>
                  {% endif %}
                {% endif %}
                {% if proposal.author_id == request.user.id or request.user.is_superuser %}
                    <a href="{% url 'update_proposal' event_slug=event.slug slug=proposal.slug %}" class="btn-flat gray text-upper" data-toggle="tooltip" title="{% trans 'Edit the proposal.' %}">
                      <i class="icon-pencil"></i> {% trans "Edit" %}
                    </a>
                    <a href="{% url 'delete_proposal' event_slug=event.slug slug=proposal.slug %}" class="btn-flat gray text-upper" data-toggle="tooltip" title="{% trans 'Delete the proposal.' %}">
                      <i class="icon-trash"></i> {% trans "Delete" %}
                    </a>
                {% endif %}
              </div>
            {% endif %}
          </div>
        {% empty %}
          <p class="lead">
            {% trans "There are no proposals to show" %}
          </p>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock content %}

{% block scripts %}
  <script src="{% static 'js/libs/jquery.linkable.js' %}"></script>
  <script src="{% static 'js/voting.js' %}"></script>

  <script type="text/javascript">
    $(function () {
      $(".linkable").linkable();
      // Collapse proposals too large
      $(".proposal-description").each(function() {
        var self = $(this);
        if (self.height() > 200) {
          self.addClass("proposal-collapse");
          self.after("<div class='show-more'><a>" + gettext('Show more') + "</a></div>");
        }
      });
      // Expand proposal on click the "Show more" link
      $(".show-more").click(function() {
        var self = $(this);
        self.prev().removeClass("proposal-collapse");
        self.remove();
      });
      // Also expand proposal on click the collapsed text area
      $(".proposal-collapse").click(function() {
        var self = $(this);
        self.removeClass("proposal-collapse");
        self.next().remove();
      });
    });
  </script>
{% endblock scripts %}

deck/templates/event/my_events.html
{% extends "layout.html" %}

{% load staticfiles %}
{% load i18n %}
{% load bootstrap3 %}
{% load deck_tags %}

{% block head_title %}{% trans "My Events" %}{% endblock %}

{% block content %}
  <div class="row header">
    <h2><strong>{% trans "My Events" %}</strong></h2>
    <a href="{% url 'create_event' %}" class="btn-flat success pull-right text-upper">
      <i class="icon-plus"></i>
      {% trans "new event" %}
    </a>
  </div>
  <div class="row" id="event-list">
    <div class="col-md-12">
      <div id="event-proposals">
        {% for event in object_list %}
          {% include "event/snippets/event_list_item.html" %}
        {% empty %}
          <p class="lead">
            {% trans "There are no events to show to you :(" %}
          </p>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock content %}

{% block scripts %}
  <script src="{% static 'js/libs/jquery.linkable.js' %}"></script>

  <script type="text/javascript">
    $(function () {
      $(".linkable").linkable();
    });
  </script>
{% endblock scripts %}

deck/templates/event/vote_block.html
{% load i18n %}
{% load deck_tags %}

<div class="text-center proposal-votes vote-buttons">
  {% if request.user|allowed_to_vote:proposal %}
    {% with request.user|get_rate_display:proposal as user_vote %}
      <p>{{ _('Use the buttons bellow to vote:') }}</p>
      {% for _, rate in vote_rates %}
        {% url 'rate_proposal' event_slug=proposal.event.slug slug=proposal.slug rate=rate as vote_url %}
        <a title="{{ rate|get_rate_title }}" data-toggle="tooltip" {% if user_vote == rate %}
           data-href="{{ vote_url }}" class="flat-icon no-hover"{% else %}
           href="{{ vote_url }}" class="flat-icon voting-link"{% endif %}>
          <i class="{{ rate }} black"></i>
        </a>
      {% endfor %}
    {% endwith %}
  {% endif %}
</div>